### DISCUSSION TITLE
Custom Authorizer function

### DISCUSSION THREAD

**Discussion by theobouwman** [logandk/serverless-wsgi#205] [Q&A] [answered]
I configured my api to be authorized with an custom authorizer function like this:
```
api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          authorizer: validate_firebase_access_token
      - http:
          path: /{proxy+}
          method: ANY
          authorizer: validate_firebase_access_token

validate_firebase_access_token:
    handler: auth.validate_firebase_access_token
```

But when I run wsgi the authorizer function won't be called... how can I fix this for local development?

**Comment by mgogoulos** [comment, marked as answer]
I guess by now you figured this out, but let me provide an example of how we use a custom authorizer in case it helps

```
functions:
  app:
    name: ourapp-service-handler 
    handler: wsgi_handler.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
          authorizer:
            name: custom_auth
            identitySource: method.request.header.Authorization
            type: token
  custom_auth:
    handler: ourapp.functionxyz.auth_authorizer
    warmup:
      enabled: false

So on ourapp.functionxyz.py there is auth_authorizer function that performs authorization. And of course requests need an Authorization header in order to be authenticated, otherwise they are not getting called at all 
```

Suggestion for @logandk : you might want to enable Github Discussions and transform threads like this on to Discussions, so that the Issues list has only issues. 
Cheers
