### DISCUSSION TITLE
[Question] Possible reasons of getting Unable to import core.wsgi.application with Django app?

### DISCUSSION THREAD

**Discussion by ShahriyarR** [logandk/serverless-wsgi#206] [Q&A]
Got the following error from the API Gateway:

```python
Wed Aug 25 14:39:51 UTC 2021 : Endpoint response body before transformations: 
{"errorMessage": "Unable to import core.wsgi.application", "errorType": "Exception", "stackTrace": ["  File \"/var/lang/lib/python3.8/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n", "  File \"/var/lang/lib/python3.8/imp.py\", line 171, in load_source\n    module = _load(spec)\n", "  File \"<frozen importlib._bootstrap>\", line 702, in _load\n", "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 848, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n", "  File \"/var/task/wsgi_handler.py\", line 115, in <module>\n    wsgi_app = import_app(config)\n", "  
File \"/var/task/wsgi_handler.py\", line 48, in import_app\n    
raise Exception(\"Unable to import {}\".format(config[\"app\"]))\n"]}
Wed Aug 25 14:39:51 UTC 2021 : Lambda execution failed with status 200 due to customer function error: Unable to import core.wsgi.application. Lambda request id: 47507347-6ca0-4452-a215-e240d4138c1a
Wed Aug 25 14:39:51 UTC 2021 : Method completed with status: 502
```

`serverless.yml`  file:

```yml
service:
  name: CustomLambdaAuth

frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local
  - serverless-offline
custom:
  userTable: user
  tableThroughputs:
    dev: "10"
  customProviderName: my.ether.login
  wsgi:
    app: core.wsgi.application
    packRequirements: false
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.local
  pythonRequirements:
    zip: true
    dockerizePip: non-linux
    invalidateCaches: true
    pythonBin: python3
    useDownloadCache: false
    useStaticCache: false
  dynamodb:
    start:
      migrate: true
    stages:
      - ${self:provider.stage}

provider:
  region: ap-southeast-2
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'
  environment:
    DEVELOPER_PROVIDER_NAME: ${self:custom.customProviderName}
    USERTABLE_NAME: ${self:custom.userTable}
    IDENTITY_POOL_ID: { Ref: CognitoIdentityPool }
    DJANGO_SETTINGS_MODULE: core.settings.local
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:ExecuteStatement"
        - "dynamodb:PartiQLSelect"
      Resource:
        - "Fn::GetAtt": [UserTable, Arn]
        - "Fn::Join":
            - "/"
            - - { "Fn::GetAtt": [UserTable, Arn] }
              - "index/*"
    - Effect: "Allow"
      Action:
        - "cognito-identity:GetCredentialsForIdentity"
        - "cognito-identity:GetOpenIdTokenForDeveloperIdentity"
      Resource:
        - "Fn::Join":
            - "/"
            - - "arn:aws:cognito-identity:#{AWS::Region}:#{AWS::AccountId}:identitypool"
              - Ref: CognitoIdentityPool

functions:
  Login: ${file(resources/functions.yml):Login}
  GetNonce: ${file(resources/functions.yml):GetNonce}
  Signup: ${file(resources/functions.yml):Signup}
  Hello: ${file(resources/functions.yml):Hello}

resources:
  Resources:
    UserTable: ${file(resources/tables.yml):UserTable}
    CognitoIdentityPool: ${file(resources/cognito.yml):CognitoIdentityPool}
    CognitoAuthorizedRole: ${file(resources/cognito.yml):CognitoAuthorizedRole}
    CognitoUnAuthorizedRole: ${file(resources/cognito.yml):CognitoUnAuthorizedRole}
    CognitoIdentityPoolRolesMapping: ${file(resources/cognito.yml):CognitoIdentityPoolRolesMapping}

package:
  exclude:
    - node_modules/**
    - venv/**
    - .dynamodb
```
