### DISCUSSION TITLE
Targeting a specific function when running `sls wsgi` commands

### DISCUSSION THREAD

**Discussion by dan-bowen** [logandk/serverless-wsgi#210] [Ideas]
Hello,

Is it possible to target a specific function when running Flask commands?

I have 2 functions with exactly the same code but different settings.

```
functions:
  api: # for serving the web requests via API gateway with a low timeout
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
    timeout: 6
  admin: # for running Flask commands (no API gateway) and a longer timeout
    handler: wsgi_handler.handler
    timeout: 900
```

It appears that running 

```
sls wsgi flask --command "db upgrade"
```

is targeting my `api` function.

The issue I am running into is the short timeout on the api function is causing my longer running Flask commands to fail. It would be great if I could target a specific function like so

```
sls wsgi flask --function admin --command "db upgrade"
```

If this is not currently supported I'm happy to investigate making a PR if you could point me in the right direction.

-Dan

P.S. Thanks for this plugin!
