### DISCUSSION TITLE
Lambda cannot find handler file after adding Layers

### DISCUSSION THREAD

**Discussion by mhihasan** [logandk/serverless-wsgi#213] [Q&A]
I am using flask. I would like to add layers to install the requirements using the `serverless-python-requirements` package by setting `layer: true`.
My project structure is as follows:

root 
- src
    - api 
        - app.py
- requirements.txt
- servereless.yml

Content of `serverless.yml` is:
```yml
service: example
 
provider:
  name: aws
  runtime: python3.7
 
plugins:
  - serverless-wsgi
  - serverless-python-requirements
 
functions:
  api:
    handler: wsgi_handler.handler
    package:
      include:
        - "./src/api/**"
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http: ANY /
      - http: ANY {proxy+}
 
custom:
   wsgi:
      app: "src/api/app.app"
      packRequirements: false
      pythonBin: python
  pythonRequirements:
      layer: true
       ....
```

As per the above configuration, I am getting this error:
`Lambda can't find the file wsgi_handler.py. Make sure that your handler upholds the format: file-name.method.`

Any help is highly appreciated. Thanks in advance.
