### DISCUSSION TITLE
Finalize Deploy Hook not working

### DISCUSSION THREAD

**Discussion by tnorlund-dsc** [logandk/serverless-wsgi#259] [Q&A]
Trying to get something to run after a `serverless deploy`. Can't get it to work using the `after:deploy:finalize` tag. Is there something else I need to add to the "serverless.yml" file?

**serverless.yml**
```yml
...
custom:
  wsgi:
    app: app.app

  scriptHooks:
    after:deploy:finalize:
      - ECHO "Deployed at `date`"
...
```
