### ISSUE TITLE
When using 'integration: lambda', serverless crashes

### ISSUE THREAD

**Issue by vdboor** [logandk/serverless-wsgi#109]
When I use the `integration: lambda` to configure response headers, the serverless-wsgi integration crashes while parsing the request:

Example configuration:
```
functions:
  app:
    handler: wsgi_handler.handler
    environment: ${self:custom.config.environment}
    events:
      - http:
          method: ANY
          path: /
          integration: lambda # Allow API gateway to edit response headers
          response:
            headers:
              X-Content-Type-Options: "'nosniff'"
              X-XSS-Protection: "'1; mode=block'"
              Strict-Transport-Security: "'max-age=16070400'"
              Referrer-Policy: "'no-referrer-when-downgrade'"
```

This resulted in the following errors:

```
{"errorMessage": "'requestContext'",
 "errorType": "KeyError",
 "stackTrace": [
 "  File \"/var/task/wsgi_handler.py\", line 109, in handler\n    return serverless_wsgi.handle_request(wsgi_app, event, context)\n",
 "  File \"/var/task/serverless_wsgi.py\", line 105, in handle_request\n    script_name = \"/{}\".format(event[u\"requestContext\"].get(u\"stage\", \"\"))\n"
]
}
```

```
{
    "errorMessage": "'dict' object has no attribute 'split'",
    "errorType": "AttributeError",
    "stackTrace": [
        "  File \"/var/task/wsgi_handler.py\", line 109, in handler\n    return serverless_wsgi.handle_request(wsgi_app, event, context)\n",
        "  File \"/var/task/serverless_wsgi.py\", line 129, in handle_request\n    \"PATH_INFO\": url_unquote(path_info),\n",
        "  File \"/var/task/werkzeug/urls.py\", line 608, in url_unquote\n    rv = _unquote_to_bytes(string, unsafe)\n",
        "  File \"/var/task/werkzeug/urls.py\", line 392, in _unquote_to_bytes\n    groups = iter(string.split(b\"%\"))\n"
    ]
}
```
