### ISSUE TITLE
Serverless Deploy Warning for - http: 'ANY {proxy+}'

### ISSUE THREAD

**Issue by ikp4success** [logandk/serverless-wsgi#153]
```Configuration warning at 'functions.app.events[1].http': value 'ANY {proxy+}' does not satisfy pattern /^(?:\*|(GET|POST|PUT|PATCH|OPTIONS|HEAD|DELETE|ANY) (\/\S*))$/i```

```
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

```

![image](https://user-images.githubusercontent.com/7339334/96289947-da3e2300-0fb3-11eb-915c-2641ea4ec554.png)

http://slss.io/configuration-validation
