### ISSUE TITLE
An error occurred: IamRoleLambdaExecution - Policy statement must contain resources.

### ISSUE THREAD

**Issue by Warqus** [logandk/serverless-wsgi#158]
I get the following error when deploying:

An error occurred: IamRoleLambdaExecution - Policy statement must contain resources. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: xxxxxxxxxxxxxxxx; Proxy: null).

This is my serverless.yaml:

```
service: ${self:custom.customName}
  
provider:
  name: aws
  stage: production
  region: eu-central-1

plugins:
  - serverless-python-requirements
  - serverless-wsgi

functions:
  functionname:
    handler: wsgi_handler.handler
    name: ${self:custom.customName}
    description: project ${self:custom.customName}
    memorySize: 512
    timeout: 28
    runtime: python3.7
    disableLogs: true
    events:
      - schedule:
          rate: rate(4 minutes)
          enabled: true
      - httpApi:
          method: '*'
          path: /{proxy+}

custom:
  customName: ${opt:name, 'test'}
  wsgi:
    app: web_backend.wsgi.application
  pythonRequirements:
    zip: true
    slim: true
```
