### ISSUE TITLE
Lambda cannot find handler file while adding Layers 

### ISSUE THREAD

**Issue by hasanul23** [logandk/serverless-wsgi#161]
I would like to add layers to install the requirements using `serverless-python-requirements` package by setting `layer: true`.
My project structure is as follows:

root 
- src
    - api 
        - app.py
- requirements.txt
- servereless.yml

Content of `serverless.yml` is:
```yml
service: example
 
provider:
  name: aws
  runtime: python3.6
 
plugins:
  - serverless-wsgi
  - serverless-python-requirements
 
functions:
  api:
    handler: wsgi_handler.handler
    layers:
       - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http: ANY /
      - http: ANY {proxy+}
 
custom:
   wsgi:
      app: "src/api/app.app"
      packRequirements: false
      pythonBin: python
  pythonRequirements:
      layer: true
       ....
```

As per the above configuration, Lambda cannot find the handler file. `wsgi_handler.py`

Any help is highly appriciated. Thanks in advance.
