### ISSUE TITLE
[Question] Getting 404 after deploying an application

### ISSUE THREAD

**Issue by ghsatpute** [logandk/serverless-wsgi#19]
I've directory structure as following 
```

├── app
│   ├── common
│   │   ├── _
│   │   
 |   ├── __init__.py
├── serverless.yml
 
```
(Some part omitted)

`__init__.py` contains a global variable `app` which flask application. 

In `serverless.yml`, I've configured the app as following app
```
functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY {proxy+}
custom:
  wsgi:
    app: app.__init__.app
```
There is one Flask API written as 

```
@app.route('/api/v1/status', methods=['GET'])
def application_status():
    """
    Application status
    :return: success
    """
```
After deploying, I get the following endpoint
```
endpoints:
  ANY - https://9vxxx7axx0.execute-api.us-east-1.amazonaws.com/dev/{proxy+}

```
When I try to send GET request on this endpoint 
`http://9xxxx7axx0.execute-api.us-east-1.amazonaws.com/dev/api/v1/status`

I get the following output:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

What am I missing?
