### ISSUE TITLE
Missing Authentication Token

### ISSUE THREAD

**Issue by joshuahoover** [logandk/serverless-wsgi#20]
I'm getting the following error when I call "/" for the simple test app below

> {"message":"Missing Authentication Token"}

**api.py**
```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def index():
    return "INDEX"

@app.route("/cats")
def cats():
    return "Cats"

@app.route("/dogs/<id>")
def dog(id):
    return "Dog = " + str(id)
```

**serverless.yml**
```
service: example

provider:
  name: aws
  runtime: python2.7

plugins:
  - serverless-wsgi

functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY {proxy+}

custom:
  wsgi:
    app: api.app
```

Calls to _/cats_ and _/dogs/x_ work fine. Oddly, calling _/_ from the API Gateway console returns successfully, but not when calling from curl or a web browser.

**Comment by logandk** [comment]
This is expected as `{proxy+}` (for unknown reasons) does not match `/`. You would need to match `/` explicitly:

```
functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
```
