### ISSUE TITLE
Missing packages for non-wsgi functions

### ISSUE THREAD

**Issue by fatalispm** [logandk/serverless-wsgi#202]
Hey, I am not sure if this is the correct repository, but I assume the problem might be with how serverless-wsgi and serverless-python-requirements interact with each other. I have the following structure:

```
custom:
  wsgi:
    app: config.wsgi.application
functions:
  api:
    handler: wsgi_handler.handler

  migrate:
    handler: migration.handler

plugins:
  - serverless-wsgi
  - serverless-python-requirements
```

The idea is to have a migrate handler that will be executed after deployment. The problem is that it fails with could not import Django", while Django is obviously installed in the handler. 

So the solution is that it appears that serverless-wsgi unzips requirements, while you need this to do manually for regular lambda functions. As stated there:
https://www.npmjs.com/package/serverless-python-requirements#dealing-with-lambdas-size-limitations
