### ISSUE TITLE
Error: ENOTDIR: not a directory, scandir `..../..../distutils-precedence.pth`

### ISSUE THREAD

**Issue by selected-pixel-jameson** [logandk/serverless-wsgi#203]
OS: MacOS 12.2.1 | Macbook Pro M1
Environment: darwin, node 14.19.0, framework 3.3.0, plugin 6.1.0, SDK 4.3.1

When I attempt to run `sls deploy` after I follow the setup instructions I get this error.

```
Deploying xxxxxxxx to stage dev

Using Python specified in "runtime": python3.8
Packaging Python WSGI handler...
Packaging required Python packages...
Linking required Python packages...

✖ Stack xxxxxxxxxxxx failed to deploy (2s)
Environment: darwin, node 14.19.0, framework 3.3.0, plugin 6.1.0, SDK 4.3.1
Credentials: Local, "key-collector" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues


Error: ENOTDIR: not a directory, scandir '/Users/......../distutils-precedence.pth'
```

My virtual environment is using Python3.8.

Folder Structure
Project
--- api.py
--- requirements.txt
--- serverless.yml

api.py
```
from flask import Flask
app = Flask(__name__)


@app.route("/cats")
def cats():
    return "Cats"


@app.route("/dogs/<id>")
def dog(id):
    return "Dog"
```

requirements.txt
```
Flask==2.0.3
Werkzeug==2.0.3
```

serverless.yml
```
service: service-name-xxxxx

provider:
  name: aws
  runtime: python3.8
  profile: aws-profile-name

plugins:
  - serverless-wsgi
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  wsgi:
    app: api.app
```

I also noticed that when I run `serverless plugin install -n serverless-wsgi` it doesn't generate a package.json file. 

This is what the folder structure looks like after I run `sls deploy`

![Screen Shot 2022-02-24 at 12 50 47 PM](https://user-images.githubusercontent.com/28204537/155588420-e8e739a3-cfa5-4634-9b6a-1d02d4f3f7eb.png)
