### ISSUE TITLE
Include/exclude files by default

### ISSUE THREAD

**Issue by jamy015** [logandk/serverless-wsgi#22]
When I use this include/exclude configuration:

```
package:
  exclude:
    - '**' # everything
  include:
    - '*.py'
```

...`.requirements` and `.wsgi_app` aren't packaged. I have to use this:

```
package:
  exclude:
    - '**' # everything
  include:
    - '*.py'
    - '.requirements/**' # Serverless WSGI
    - '.wsgi_app' # Serverless WSGI
```

It seems useful to include `.requirements/**` and `.wsgi_app`, even when that's not specified. In the same vein, it seems useful to exclude `node_modules/serverless-wsgi/**`. (Similarly, Serverless itself excludes `.serverless\**`, even when that's not specified.
