### ISSUE TITLE
using Ref or Fn::ImportValue sets environment variable to [object Object]

### ISSUE THREAD

**Issue by OliverGavin** [logandk/serverless-wsgi#53]
I'm trying to use environment variables to access CF stack outputs and the following works for me in Lambda:

```
  environment:
    VAR1:
      Fn::ImportValue: "UserPool::Id"
    # OR
    VAR2:
      Ref: UserPool
```

But it won't work for `sls wsgi serve`:

```
>>> os.environ['VAR1']
[object Object]
>>> os.environ['VAR2']
[object Object]
```

I don't know much about how serverless plugins work but my best guess is that it comes from here:
https://github.com/logandk/serverless-wsgi/blob/master/index.js#L163

Is this a serverless problem? or would it be possible for serverless-wsgi to store the resolved Fn::ImportValues on `sls deploy` and reproduce them later? or pull from cloudformation?
