### ISSUE TITLE
Does not work with serverless-python-requirements package.individually: true

### ISSUE THREAD

**Issue by diegojancic** [logandk/serverless-wsgi#85]
This module files are not included when used together with `serverless-python-requirements` and the `package.individually` option set to true. The files are put in the root package (which does not get uploaded) and not in each of the files that are actually uploaded.

Example configuration file (some parts removed): 

```
functions:
  app:
    module: web
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  image_processor:
    module: imageprocessor
    handler: process.lambda_handler

package:
  individually: true
  exclude:
    - node_modules/**
    - web/env/**
    - imageprocessor/env/**

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements
  - serverless-wsgi
```

The `web` module includes only the application files, but not the ones to work with APIG.  It could also be a bug in the other plugin, but since this one already integrates somehow with the other one, I assume the problem is here.
