### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by eon01** [logandk/serverless-wsgi#90]
Hi,

I had this error when I run ` sls wsgi serve `

```
Traceback (most recent call last):
  File "[...]/app/node_modules/serverless-wsgi/serve.py", line 51, in <module>
    serve(*sys.argv[1:])
  File "[...]/app/node_modules/serverless-wsgi/serve.py", line 28, in serve
    wsgi_app = getattr(wsgi_module, wsgi_fqn[1])
IndexError: list index out of range
```

When I changed serve.py line 28 from ` wsgi_app = getattr(wsgi_module, wsgi_fqn[1]) ` to    
 ` wsgi_app = getattr(wsgi_module, wsgi_fqn[0]) ` I stopped having the error.

```
sls --version
1.38.0

python --version
Python 3.6.7
```

And this is my serverless.yml file

```
service: xx

plugins:
  - serverless-python-requirements
  - serverless-wsgi
package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  wsgi:
    app: app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    NLTK_DATA: ./nltk_data
    WPM: 200

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
```

https://github.com/logandk/serverless-wsgi/blob/d10955598267c3fb5045ffd79be592ae5f608b7c/serve.py#L28
