### ISSUE TITLE
AttributeError with `wsgi serve` when package `individually: true` and `module` provided

### ISSUE THREAD

**Issue by pranavbadami** [logandk/serverless-wsgi#98]
Hi, I believe I'm encountering a problem when I'm combining the `sls wsgi serve` command with individually packaged functions. Here's my directory setup, for reference:
```
├── api
│   ├── api.py
│   ├── requirements.txt
├── compute
│   ├── compute_functions.py
│   └── requirements.txt
├── serverless.yml
```
I'm initializing a Flask app in `api/api.py`, while `compute/compute_functions.py` contains a vanilla `handler()` function.

Here's how my `serverless.yml` is set up:
```
package:
  individually: true

functions:
  api:
    handler: wsgi_handler.handler
    module: api
    events:
      ...
  compute:
    handler: compute_functions.handler
    module: compute
    ...

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
  wsgi:
    app: api/api.app
```

This setup works fine when I deploy to AWS; however, I'm running into issues when I try to run the WSGI service locally. Specifically, I get the following debug output:
```
> sls wsgi serve
Serverless: Using Python specified in "runtime": python3.7
Traceback (most recent call last):
  File "/Users/pranav/Documents/numina/numina-graph/node_modules/serverless-wsgi/serve.py", line 51, in <module>
    serve(*sys.argv[1:])
  File "/Users/pranav/Documents/numina/numina-graph/node_modules/serverless-wsgi/serve.py", line 28, in serve
    wsgi_app = getattr(wsgi_module, wsgi_fqn[1])
AttributeError: module 'api' has no attribute 'app'
```
I'm able to workaround this issue by commenting out the `module: api` and `module: compute` lines in `serverless.yml` when running locally, and leaving them in when deploying. Of course, I don't want to do this moving forward, and I would love some help getting past this issue. Thanks in advance!
